tap "boz/repo"
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# GNU Tools
brew "coreutils"
brew "bash"
brew "binutils"
brew "diffutils"
brew "findutils"
brew "file-formula"
brew "gawk"
brew "grep"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gpatch"
brew "gnutls"
brew "gzip"
brew "less"
brew "ncdu"
brew "make"
brew "rsync"
# brew "screen" # Use tmux instead
brew "telnet"
brew "tree"
brew "watch"
brew "wdiff"
brew "wget"
brew "xz"
brew "zsh"


brew "ack"
brew "autojump"
brew "corretto"
brew "python"
brew "ansible"
brew "openssl"
brew "openssh"
# brew "azure-cli" # Removed (Non-GCP)
# brew "awscli" # Removed (Non-GCP)
brew "exa"
brew "kind"
brew "maven"
brew "asciinema"
brew "bat"
# brew "docker-completion" # Removed
# brew "docker-machine-driver-xhyve" # Removed
brew "git"
brew "go"
brew "govc"
brew "hugo"
brew "peco"
brew "ripgrep"
brew "terraform"
brew "thefuck"
brew "tig"
brew "helm"
# brew "kops" # Removed (AWS focused)
brew "htop"
brew "hub"
# brew "hyperkit", link: false # Removed
brew "iperf3"
brew "istioctl"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kubectx"
brew "markdown"
# brew "minikube" # Removed
# brew "openshift-cli" # Removed
brew "sshuttle"
brew "stern"
brew "tmate"
brew "tmux"
brew "youtube-dl"
brew "zsh-completions"

# Cloud Engineering Tools
brew "k9s"
brew "yq"
brew "grpcurl"
brew "age"
brew "sops"
brew "google-cloud-sdk"
