# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Truecolor and 256-color terminal support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Large scrollback history for cloud logs
set -g history-limit 50000

# Automatically set window title and don't let it change
set-option -g set-titles on
set-option -g allow-rename off

# Use C-a as prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind-key a send-key C-a

# Start numbering at 1 and renumber when windows close
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind * choose-session  # choose session interactively

# Split panes in current working directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Quick config reload with Prefix + r
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"

source-file "${HOME}/.dotfiles/blue.tmuxtheme"

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'